# Generated by Django 5.2.8 on 2025-11-23 02:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Foodie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('waktu', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Foodies',
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('lokasi', models.CharField(max_length=200)),
                ('kategori', models.CharField(choices=[('kafe', 'Cafe'), ('fine_dining', 'Fine Dining Restaurant'), ('casual_dining', 'Casual Dining Restaurant'), ('fast_casual', 'Fast Casual Dining'), ('fast_food', 'Fast Food Restaurant')], max_length=50)),
                ('no_telp', models.CharField(max_length=20)),
                ('deskripsi', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Restaurants',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('komentar', models.TextField()),
                ('waktu_review', models.DateTimeField(auto_now_add=True)),
                ('foodie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='restaurant.foodie')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='restaurant.restaurant')),
            ],
            options={
                'verbose_name_plural': 'Reviews',
                'ordering': ['-waktu_review'],
            },
        ),
    ]
